Repository sturdy-dev/codeball-action, pull requests merged in 2022-06, with the labels that each got.

#20 Anonymous usage statistics
  action.yml
  approver/action.yml
  labeler/action.yml
  src/approver/main.ts
  src/baller/main.ts
  src/labeler/main.ts
  src/lib/track/track.ts
  src/status/main.ts
Labels: codeball:approved

#21 Improve <details> layouting in Safari
  README.md
Labels: codeball:approved

#25 Fix imports of github libraries
  hack/build-beta.sh
  src/approver/main.ts
  src/baller/main.ts
  src/labeler/main.ts
  src/lib/actions/input.ts
  src/status/main.ts
Labels: codeball:needs-review

#28 Add summary with link to dashboard
  hack/run-e2e-tests.sh
  src/baller/main.ts
Labels: codeball:needs-review

#35 Add dashboard link to the codeball approve message
  src/approver/main.ts
Labels: codeball:needs-review

#37 Update README templates with feature flag options
  README.md
Labels: codeball:needs-review

#39 approver: use templating to construct message
  src/approver/main.ts
Labels: codeball:approved

#42 labeler: only remove labels if they are set
  src/labeler/main.ts
Labels: codeball:approved

#46 small import fixes
  src/baller/main.ts
  src/labeler/main.ts
  src/status/main.ts
Labels: codeball:needs-review

#48 labler fallback
  src/labeler/main.ts
  src/lib/github/pulls/index.ts
Labels: codeball:needs-review

#50 labler: fix api path
  src/lib/github/pulls/index.ts
Labels: codeball:approved

#49 README: document codeball-ai-writer
  README.md
Labels: codeball:approved, codeball:needs-review

#52 action: make our action similar to the default one
  .github/workflows/codeball.yml
Labels: codeball:approved

#53 examples: skip drafts
  README.md
  examples/skip-drafts.yaml
Labels: codeball:approved
